export const PURCHASE_FILTERS_FORM_FIELDS = [
    { name: 'id', type: 'number' },
    { name: 'sellerId', type: 'number' },
    // { name: 'projectedSubtotal', type: 'number' },
    // { name: 'projectedShippingFee', type: 'number' },
    // { name: 'projectedOtherFee', type: 'number' },
    // { name: 'projectedTax', type: 'number' },
    { name: 'chargedSubtotal', type: 'number' },
    { name: 'chargedShippingFee', type: 'number' },
    { name: 'chargedOtherFee', type: 'number' },
    { name: 'chargedTax', type: 'number' },
    { name: 'statusCode', type: 'number' },
    { name: 'statusName', type: 'text' },
    { name: 'estimatedDeliveryDate', type: 'date' },
    { name: 'orderIdFromSellerSite', type: 'text' },
    { name: 'shippingIdFromCarrier', type: 'text' },
    { name: 'notes', type: 'text' },
    { name: 'createdAt', type: 'date' },
    { name: 'updatedAt', type: 'date' },
    // { name: 'purchaseItems', type: 'text' }
];